// automatically generated by the FlatBuffers compiler, do not modify

package TMSDKClient.FlatBuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class CallResult extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static CallResult getRootAsCallResult(ByteBuffer _bb) { return getRootAsCallResult(_bb, new CallResult()); }
  public static CallResult getRootAsCallResult(ByteBuffer _bb, CallResult obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public CallResult __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte code() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String message() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer messageAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer messageInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createCallResult(FlatBufferBuilder builder,
      byte code,
      int messageOffset) {
    builder.startTable(2);
    CallResult.addMessage(builder, messageOffset);
    CallResult.addCode(builder, code);
    return CallResult.endCallResult(builder);
  }

  public static void startCallResult(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addCode(FlatBufferBuilder builder, byte code) { builder.addByte(0, code, 0); }
  public static void addMessage(FlatBufferBuilder builder, int messageOffset) { builder.addOffset(1, messageOffset, 0); }
  public static int endCallResult(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public CallResult get(int j) { return get(new CallResult(), j); }
    public CallResult get(CallResult obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

