// automatically generated by the FlatBuffers compiler, do not modify

package TMSDKClient.FlatBuffers;

public final class CallDefine {
  private CallDefine() { }
  public static final byte TM_UNITY_SDK_CALLBACK_GAMEOBJECT = 0;
  public static final byte unityCallandroid = 1;

  public static final String[] names = { "TM_UNITY_SDK_CALLBACK_GAMEOBJECT", "unityCallandroid", };

  public static String name(int e) { return names[e]; }
}

