// automatically generated by the FlatBuffers compiler, do not modify

package TMSDKClient.FlatBuffers;

public final class PlatformSDKMethodName {
  private PlatformSDKMethodName() { }
  public static final byte init = 0;
  public static final byte login = 1;
  public static final byte logout = 2;
  public static final byte pay = 3;

  public static final String[] names = { "init", "login", "logout", "pay", };

  public static String name(int e) { return names[e]; }
}

