// automatically generated by the FlatBuffers compiler, do not modify

package TMSDKClient.FlatBuffers;

public final class ResultCode {
  private ResultCode() { }
  public static final byte Success = 0;
  public static final byte Exception = 1;

  public static final String[] names = { "Success", "Exception", };

  public static String name(int e) { return names[e]; }
}

