// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMSDKClient.FlatBuffers
{

public enum CallDefine : sbyte
{
  TM_UNITY_SDK_CALLBACK_GAMEOBJECT = 0,
  unityCallandroid = 1,
};


}
