// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMSDKClient.FlatBuffers
{

public enum PlatformSDKMethodName : sbyte
{
  init = 0,
  login = 1,
  logout = 2,
  pay = 3,
};


}
