version: "3.0"
services: 
  nexus3:
    image: sonatype/nexus3:latest
    volumes: 
      - nexus3:/nexus-data
    ports: 
      - mode: host
        protocol: tcp
        published: 5001
        target: 8081
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.labels.nexus3-server == true
          



volumes:
  nexus3: