// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace TMSDKClient.FlatBuffers
{

public enum ResultCode : sbyte
{
  Success = 0,
  Exception = 1,
};


}
